name: Build and Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/historicalsite:latest

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './be_historicalsite/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./be_historicalsite
        run: npm ci
      
      - name: Run backend tests
        working-directory: ./be_historicalsite
        run: npm run test
  build-and-deploy:
    name: Build and Deploy Both Services
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker --version
          docker compose --version

      - name: Create .env file
        run: |
          cat > .env <<EOF
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          EOF

      - name: Build and start both services
        run: docker compose up -d --build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images to Docker Hub
        run: |
          # Tag and push backend image
          docker tag historicalsite_backend ${{ secrets.DOCKER_USERNAME }}/historicalsite-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/historicalsite-backend:latest
          
          # Tag and push frontend image
          docker tag historicalsite_frontend ${{ secrets.DOCKER_USERNAME }}/historicalsite-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/historicalsite-frontend:latest
